import { NextRequest, NextResponse } from "next/server";
import { DEMO_INTERVIEW_QUESTIONS } from "@/lib/demo-data";
import {
  INTERVIEW_SYSTEM_PROMPT,
  INTERVIEW_ANALYSIS_PROMPT,
} from "@/lib/prompts";
import { getAIClient, parseAIResponse } from "@/lib/ai-client";
import type { InterviewMode, AnswerAnalysis } from "@/types";

interface InterviewRequestBody {
  mode: InterviewMode;
  messages: { role: "ai" | "user"; content: string }[];
  currentQuestion?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: InterviewRequestBody = await request.json();
    const { mode, messages, currentQuestion } = body;

    if (!mode || !["hr", "technical", "startup", "product", "sales", "marketing"].includes(mode)) {
      return NextResponse.json(
        { error: "Invalid interview mode" },
        { status: 400 }
      );
    }

    // Validate message array
    if (messages && (!Array.isArray(messages) || messages.length > 50)) {
      return NextResponse.json(
        { error: "Invalid or too many messages" },
        { status: 400 }
      );
    }

    // Sanitize user inputs to prevent basic prompt injections and strip raw HTML
    const sanitizedMessages = messages.map(m => ({
      ...m,
      content: typeof m.content === "string" ? m.content.replace(/<[^>]*>?/gm, '').trim() : ""
    }));

    // Validate individual message lengths after sanitization
    if (
      sanitizedMessages.some(
        (m: { content?: string }) =>
          typeof m.content !== "string" || m.content.length > 5000 || m.content.length === 0
      )
    ) {
      return NextResponse.json(
        { error: "Message content invalid or too long (max 5000 chars)" },
        { status: 400 }
      );
    }

    const { openai, model: aiModel, apiKey, isGemini } = await getAIClient(request);

    if (!openai || !apiKey) {
      return NextResponse.json(
        { error: "No API key configured. Please add an OpenAI or Gemini API key in settings." },
        { status: 401 }
      );
    }

    // Real mode with OpenAI

    let analysis: AnswerAnalysis | undefined;

    // Analyze the user's last answer if there is one
    if (
      currentQuestion &&
      sanitizedMessages.length > 0 &&
      sanitizedMessages[sanitizedMessages.length - 1].role === "user"
    ) {
      const userAnswer = sanitizedMessages[sanitizedMessages.length - 1].content;
      const analysisPrompt = INTERVIEW_ANALYSIS_PROMPT.replace(
        "{question}",
        currentQuestion
      ).replace("{answer}", userAnswer);

      try {
        const analysisCompletion = await openai.chat.completions.create({
          model: aiModel as string,
          messages: [
            {
              role: "system",
              content:
                "You are an interview coach. Respond with valid JSON only.",
            },
            { role: "user", content: analysisPrompt },
          ],
          temperature: 0.7,
          max_tokens: 500,
          ...(isGemini ? {} : { response_format: { type: "json_object" as const } }),
        });

        const analysisText = analysisCompletion.choices[0]?.message?.content;
        if (analysisText) {
          try {
            analysis = parseAIResponse(analysisText);
          } catch (e) {
            console.error("Failed to parse evaluation JSON:", analysisText);
          }
        }
      } catch (apiError: any) {
        console.error("Analysis API failed:", apiError);
        return NextResponse.json(
          { error: `AI analysis failed: ${apiError.message || "Unknown error"}` },
          { status: 500 }
        );
      }
    }

    // Generate next question
    const systemPrompt =
      INTERVIEW_SYSTEM_PROMPT[mode as keyof typeof INTERVIEW_SYSTEM_PROMPT];

    const openaiMessages: { role: "system" | "user" | "assistant"; content: string }[] = [
      { role: "system", content: systemPrompt },
      ...sanitizedMessages.map((m: any) => ({
        role: (m.role === "ai" ? "assistant" : "user") as "assistant" | "user",
        content: m.content as string,
      })),
    ];

    let question: string | null = null;
    try {
      const completion = await openai.chat.completions.create({
        model: aiModel as string,
        messages: openaiMessages,
        temperature: 0.8,
        max_tokens: 500,
      });
      question = completion.choices[0]?.message?.content || null;
      if (!question) throw new Error("No question generated by AI");
    } catch (apiError: any) {
      console.error("Question API failed:", apiError);
      return NextResponse.json(
        { error: `AI question generation failed: ${apiError.message || "Unknown error"}` },
        { status: 500 }
      );
    }

    return NextResponse.json({
      question,
      analysis,
      isComplete: !question,
    });
  } catch (error) {
    console.error("Interview API error:", error);
    return NextResponse.json(
      { error: "Failed to process interview request" },
      { status: 500 }
    );
  }
}
